version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
    - echo entered the build phase

artifacts:
  files:
    - index.html
    - README.md
    - favicon.ico
    - styles/main.css
    - images/*
