version: 0.1

phases:
  build:
  runtime-versions:
   nodejs: 7.0.0
  build:
    commands:
      - echo Nothing to do yet
artifacts:
  files:
    - index.html
    - favicon.icon
    - styles/main.css
    - images/*
