version: 0.2

phases:
  install:|
      finally:
        - echo this always runs
      pre_build:
        commands:
          - | echo entered the pre_build phase...
          finally:
            - echo this always runs
  build:
    commands:
    - echo entered the build phase
 phase...
artifacts:
  files:
    - index.html
    - favicon.icon
    - styles/main.css
    - images/*
