version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 7.0.0
  build:
    commands:
    - echo entered the build phase

artifacts:
  files:
    - index.html
    - favicon.icon
    - styles/main.css
    - images/*
